#!/usr/bin/env php
<?php
// composer auto loader
require __DIR__ . '/vendor/autoload.php';

$option = isset($argv[1]) ? trim($argv[1]) : false;
$arg1   = isset($argv[2]) ? trim($argv[2]) : false;

// setup xivapi
$api = new \XIVAPI\XIVAPI(\XIVAPI\XIVAPI::STAGING);

$results = $api->market->item(3, [ 'Phoenix' ]);

print_r($results);
die;
