#!/usr/bin/env php
<?php
// composer auto loader
require __DIR__ . '/vendor/autoload.php';

$option = isset($argv[1]) ? trim($argv[1]) : false;
$arg1   = isset($argv[2]) ? trim($argv[2]) : false;

// setup xivapi
$api = new \XIVAPI\XIVAPI();

// set env key
$api->environment->key('my_api_key');

$items = $api->search
    ->indexes(['item'])
    ->filter('ItemSearchCategory.ID', 10, \XIVAPI\Api\SearchFilters::EQUAL_TO)
    ->limit(500)
    ->sort('LevelItem', 'desc')
    ->columns(['ID','Name'])
    ->results();

print_r($items);
